Implement InputMediaBuilder
grammyjs/grammY pull request #210
Opened 2022-05-16 14:28 UTC by WingLim

Create `builders` for other builder.

InputMediaBuilder methods:

Basic methods:

- add
- build

Advanced methods:
All these methods use `Omit` to remove `type` property for each different InputMedia, so that user can use it more convenient.

- photo
- video
- animation
- audio
- document

TODO:
- [ ] Documentation for the builder

Close #101

2022-05-16 14:59 UTC, WingLim commented
@KnorpelSenf Plz take a look the code, if it's good for you, then I will write the documentation for it.

2022-05-16 16:03 UTC, roj1512 reviewed
I recommend changing the file name to something simpler (one word), or to `input_media_builder.ts`. So it is consistent with either the other grammY files or official Deno libraries.

2022-05-16 21:43 UTC, WingLim commented
The static method `from` comes from #104, and according to https://github.com/grammyjs/grammY/pull/211#issuecomment-1128112737, we can use constructor to do this job.

I don't know which one is better?

2022-05-19 09:16 UTC, WingLim commented
> The static method `from` comes from #104, and according to [#211 (comment)](https://github.com/grammyjs/grammY/pull/211#issuecomment-1128112737), we can use constructor to do this job.
> 
> I don't know which one is better?

I have added them both, in case someone like the other style more.

2022-05-19 16:44 UTC, KnorpelSenf requested changes
What do you think about also providing something like `InputMediaBuilder.Photo` and the like? That way, we could create stuff using `InputMediaBuilder.Photo.from(...)` which can be passed to `InputMediaBuilder.from` in turn. In addition, it allows for `new InputMediaBuilder.Photo()` with chained method calls. The main builder could then also support the sub-builders, so that `build` does not have to be called on all of them.

I am also wondering if there is a better way to create these things than specifying a config object for every entry. Perhaps this is already possible with the idea described above?

2022-05-19 16:44 UTC, KnorpelSenf commented on src/convenience/builders/input_media.ts
> +    constructor(media?: InputMedia[]) {
This can be merged with the field declaration.

2022-05-19 16:44 UTC, KnorpelSenf commented on src/convenience/builders/input_media.ts
> +    InputMediaPhoto,
```suggestion
    type InputMedia,
    type InputMediaAnimation,
    type InputMediaAudio,
    type InputMediaDocument,
    type InputMediaPhoto,
```

2022-05-20 07:35 UTC, WingLim commented
I have a idea about this.

Add a `fromType` static method which accept 2 params:
1. The media array
2. The type of `InputMedia`

Then use a `GenericInputMediaBuilder` to constraint the type of the specific `InputMedia`(e.g. `InputMediaPhoto`) builder.

Let me show you the code to explain it more.

2022-08-02 10:14 UTC, KnorpelSenf commented
Please also add some tests.

2023-06-18 09:43 UTC, KnorpelSenf requested changes
I now think it is overkill to have a builder for an array. I remember thinking that I would like to abstract that away, but now I believe this would be overkill and take it too far.

I used the rest your changes to create #437. This will subsequently be closed. Thank you anywy for this contribution (and sorry for the long delay)!

2023-06-25 22:42 UTC, closed without merging