Update typings for `prices` field
grammyjs/grammY pull request #367
Opened 2023-02-11 19:29 UTC by LWJerri

Hello dear developers! I made some changes in the typings for the `prices` field, because the description is outdated and I added new info, e.g max objects in prices.

2023-02-13 15:21 UTC, LWJerri commented
What do I need do to?

2023-02-13 15:31 UTC, KnorpelSenf commented
Wait until I have time. I am a little busy these days, sorry. On first sight, these changes are excellent, but I want to go through the docs once more and actually check that nothing else was forgotten. As soon as I'm done with that, I'll approve and merge :)

2023-03-08 23:46 UTC, KnorpelSenf requested changes
There changes are incorrect.

2023-03-08 23:46 UTC, KnorpelSenf commented on src/core/api.ts
> +     * @param prices Price breakdown, a list of components (e.g. product price and name), max 15 objects.
I don't know where from you're taking this. https://core.telegram.org/bots/api#sendinvoice says that the current version is correct.

2023-03-19 10:44 UTC, KnorpelSenf commented
Closing due to inactivity.

2023-03-19 10:44 UTC, closed without merging