docs: update README
grammyjs/grammY pull request #455
Opened 2023-06-29 18:28 UTC by roj1512

2023-06-29 18:29 UTC, roj1512 commented
Which one is correct?

- grammY api reference
- grammY API reference
- grammY API Reference

2023-06-29 19:05 UTC, KnorpelSenf commented
> Which one is correct?
> 
> * grammY API reference
> * grammY API Reference

I have no idea.

2023-06-29 19:06 UTC, KnorpelSenf approved these changes
I was waiting for this lol, would've done it myself in a few days

2023-06-29 19:06 UTC, KnorpelSenf commented
grammY api reference *hides away*

2023-06-30 13:44 UTC, KnorpelSenf requested changes
Let's use _grammY API reference_ as we do [here](https://grammy.dev/guide).

2023-06-30 20:10 UTC, KnorpelSenf commented on README.md
> +### [Telegram Bot API reference](https://core.telegram.org/bots/api)
Now you're using grammY style for TG stuff. Shouldn't it be title case? Yes, we will then have two different casings of the same word

2023-06-30 20:15 UTC, roj1512 commented
I modified the wrong line.

2023-07-01 08:45 UTC, KnorpelSenf approved these changes
Thanks!

2023-07-01 08:45 UTC, merged