build: add `bundling/build-cjs.ts`
grammyjs/grammY pull request #469
Opened 2023-07-18 04:45 UTC by wojpawlik

Alternative to https://github.com/fromdeno/deno2node/issues/40: reusable script with embedded `compilerOptions`. Feel free to revert any changes you don't like.

2023-08-07 08:28 UTC, KnorpelSenf requested changes
I like these changes a lot! This is a great stepping stone towards #372

2023-08-07 08:28 UTC, KnorpelSenf commented on bundling/bundle-web.ts
> +    cache.load(specifier.replace(/\.deno\.ts$/, ".web.ts"));
Could you revert to using explicit string operations rather than regex? I inherently don't trust ~~regex~~ humans brains to read regex correctly

2023-08-07 08:35 UTC, KnorpelSenf approved these changes

2023-11-21 17:32 UTC, wojpawlik commented on deno.jsonc
> -        "contribs": "deno run --allow-env --allow-read --allow-write=. --allow-net=api.github.com npm:all-contributors-cli"
Accidentally removed this while resolving conflicts 🙈 pin to a major release and tighten permission when restoring.

2024-03-22 19:42 UTC, KnorpelSenf requested changes
Can the web build be integrated into the CJS+ESM build script so that a single script invocation builds the entire package?

2024-03-23 15:06 UTC, wojpawlik commented
Yes, if you forego bundling, and use v2-only [`Context::changeRuntimeTo()`](https://github.com/fromdeno/deno2node/blob/4815ee0e014f1a6c0cd06b0a7b8d07cf63a0ee1c/src/context.ts#L51). I suggest waiting until runtime switching is added to grammY 2.0.

2024-05-16 14:13 UTC, KnorpelSenf commented
I think we're just going to migrate to JSR and cross-publish the packages to npm so that we can get rid of the build step entirely

2024-05-16 14:46 UTC, KnorpelSenf commented
Will likely be superseded by #559

2024-05-17 11:35 UTC, KnorpelSenf commented
Decided

2024-05-17 11:35 UTC, closed without merging